/icp_registration:
  ros__parameters:
    rough_iter_: 10
    refine_iter_: 7
    rough_leaf_size: 0.4
    refine_leaf_size: 0.1
    pcd_path: ""
    map_frame_id: "map"
    odom_frame_id: "odom"
    range_odom_frame_id: "lidar_odom"
    laser_frame_id: "livox_frame"
    pointcloud_topic: "/livox/lidar/pointcloud"
    thresh: 0.1
    # xy_offset: 0.15
    x_offset: 0.15
    y_offset: 0.10
    yaw_offset: 20.0
    # yaw_resolution: 10.0
    yaw_resolution: 2.0
    # roll_offset: 3.0
    # roll_resolution: 0.1
    initial_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # x,y,z,roll,pitch,yaw
    # initial_pose: [2, 0.5, 0.0, 0.0, 0.0, 0.0]