/small_gicp_relocalization:
  ros__parameters:
    use_sim_time: false
    num_threads: 4
    num_neighbors: 10
    global_leaf_size: 0.25
    registered_leaf_size: 0.25
    max_dist_sq: 1.0
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    lidar_frame: "livox_frame"
    # The prior_pcd_file does not need to be specified since it going to be set by defaults in launch.
    prior_pcd_file: "
